# Generated by Django 5.0 on 2023-12-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CosmoPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('born', models.CharField(max_length=255, verbose_name='Born')),
                ('died', models.CharField(max_length=255, verbose_name='Died')),
                ('cause_of_death', models.CharField(max_length=255, verbose_name='Cause of death')),
                ('nationality', models.CharField(max_length=255, verbose_name='Nationality')),
                ('time_in_space', models.CharField(max_length=255, verbose_name='Time in space')),
                ('missions', models.CharField(max_length=255, verbose_name='Missions')),
                ('years_of_service', models.CharField(max_length=255, verbose_name='Years of service')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kosmonavt',
                'verbose_name_plural': 'Kosmonavtlar',
                'ordering': ('-created_at',),
            },
        ),
    ]
